### ISSUE TITLE
Update OpenWrt packages

### ISSUE THREAD

**Issue by aparcar** [aparcar/asu#109]
The server OpenWrt package is outdated and should up updated

**Comment by FreifunkUFO** [comment]
which package-name do you mean? on which server?

**Comment by aparcar** [comment]
the server itself could be installed as an package. it's however outdated and therefore needs an update

**Comment by dangowrt** [comment]
There is now a software package called `asu` available only on OpenWrt for the `x86/64` target. Paul said he'd create an nginx configuration and asu-nginx package pulling both nginx and asu and configuring everything (except for permanent storage of builders, images and database)

**Comment by aparcar** [comment]
Please see here https://github.com/openwrt/packages/pull/8380

**Comment by aparcar** [comment]
Removed for now, I'll offer it as an container.
