### ISSUE TITLE
"error 405 not allowed" when accessing test server from Attended Sysupgrade LUCI package

### ISSUE THREAD

**Issue by tlaurion** [aparcar/asu#133]
@aparcar : I get a` error 405 not allowed` accessing test server from Attended Sysupgrade LUCI package.

Configured Attended Sysupgrade server: `https://as-test.stephen304.com/chef`

Request url:
`https://as-test.stephen304.com/chef/api/upgrade-check`

Request header:
```
Host: as-test.stephen304.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: http://typycalhiddentorservice.onion
Connection: keep-alive
```

Header Response:
```
HTTP/1.1 405 Not Allowed
Server: nginx/1.10.3
Date: Wed, 24 Oct 2018 16:00:47 GMT
Content-Type: text/html
Content-Length: 173
```

**Comment by tlaurion** [comment]
@aparcar : Am I doing something wrong? Is my isp blocked or something? :|

**Comment by aparcar** [comment]
The correct url is ` https://as-test.stephen304.com/api/upgrade-check`, without the *chef* in between :+1:

**Comment by aparcar** [comment]
However, there seems to be a bad SQL query which basically kills the server once you ask for an upgrade. I'll have to fix that first

**Comment by tlaurion** [comment]
@aparcar: Any update?

**Comment by aparcar** [comment]
Please try again, while [this](https://github.com/aparcar/attendedsysupgrade-server/pull/141) isn't perfect, it should to the job for now...

**Comment by aparcar** [comment]
I reworked the server and app and currently everything seems to work, please reopen in case of trouble!
