### ISSUE TITLE
Add INSTALL documentation for ubuntu/debian/openwrt

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/asu#138]
please provide documentation howto install and host such a server on a standard ubuntu, debian and/or openwrt installation. (including chef)

see also https://github.com/aparcar/attendedsysupgrade-server/issues/135, which were mentioned before, but install method WITHOUT vagrant,ansibel, docker and virtualbox would be nice.

**Comment by aparcar** [comment]
Hi @FreifunkUFO , the installation process is somewhat complex, as it does not only include cloning a repo. I added some dev steps, however they might be incomplete.

https://github.com/aparcar/attendedsysupgrade-server/tree/mixing#development

Please reopen this issue if steps are missing, also please provide PRs to improve the documentation

**Comment by FreifunkUFO** [comment]
hey @aparcar, you wrote
> Please reopen this issue

but, i cant reopen issues

**Comment by FreifunkUFO** [comment]
and @aparcar wrote 
> Setting up Postgresql

would be nice to have these commands to do that. (f.i. "passwd postgres" wasnt useful ) i found some, but not working for me yet.
and, i think the database setting is missing in the config.yml? but i dont know correct syntax by now.

**Comment by aparcar** [comment]
I rewrote the installation manual (which is now much simpler). So for now you don't need Vagrant, Docker or any other fancy setup. I'll add a `pip` install-able package soonish.
