### ISSUE TITLE
banner.html

### ISSUE THREAD

**Issue by FreifunkUFO** [aparcar/asu#155]
should that file being loaded from chef or from asu-server?
at the moment it seems to be from asu-server (of course atm with 404)

![grafik](https://user-images.githubusercontent.com/2579265/53021063-a31f1380-3458-11e9-9414-63e047e15958.png)

**Comment by aparcar** [comment]
This is normal behavior if no banner is set, no worries

**Comment by FreifunkUFO** [comment]
where can i "set" the banner?

**Comment by aparcar** [comment]
rename banner.html.example to banner.html and fill it with whatever html content you like

**Comment by FreifunkUFO** [comment]
do you mean https://github.com/libremesh/chef/commit/fa5c385518278ba3b07c273420b68c9ca005ba73 ?
i have a chef-directory with banner.html and it is not loaded from that chef-webserver. (but browser tries to load it from the asu-server. see screenshot above!
but inside view-py-file i cant see any banner-html-tasks.

so that shouldnt be "normal behaviour", please reopen this ticket!

p.s. 
yes i know, i can fill html into that file.. btw: its not an html-file, but only a html template file.

**Comment by aparcar** [comment]
I need to add a real nginx config..m

**Comment by aparcar** [comment]
No longer used in new frontend.
