### ISSUE TITLE
opkg is installed automatically

### ISSUE THREAD

**Issue by McChary** [aparcar/asu#158]
I always try the latest compilations of openwrt and remove many packages that I do not use to accelerate the device, but when I remove opkg from the list it seems to be installed automatically.

You can see the created image.
https://chef.libremesh.org/json/openwrt/snapshots/ar71xx/tiny/tl-wr841-v8/5017f55374dcd40/buildlog-16d10b5f1c774e8.txt

**Comment by aparcar** [comment]
I tried the same [here](https://chef.libremesh.org/#34633af51b05) and it works as excepted. Please send the list of packages used in the chef frontend.

**Comment by McChary** [comment]
Well apparently in version 18.06.2 you can remove opkg, but in the snapshot versions the first time you open the thread was installed automatically, I just tried and now a construction error is coming out.

https://chef.libremesh.org/download/faillogs/faillog-9e251fa74e79.txt

![screenshot_7](https://user-images.githubusercontent.com/47784392/53926734-ff8a5180-405a-11e9-887f-fd95cc8862ba.png)

Package list:
ip6tables
odhcp6c
base-files
mtd
fstools
busybox
wpad-mini
kmod-gpio-button-hotplug
logd
swconfig
kmod-ath9k
dnsmasq
dropbear
ppp
netifd
ppp-mod-pppoe
uci
libc
uclient-fetch
uboot-envtools
kmod-ipt-offload
libgcc
odhcpd-ipv6only
iptables
firewall
luci

**Comment by aparcar** [comment]
opkg removal seem to work when you specify the package you want to remove, see screenshot. Please test the new server at https://chef.libremesh.org/


![image](https://user-images.githubusercontent.com/16000931/75202986-0c430200-5711-11ea-8c35-88262aed76f8.png)

**Comment by aparcar** [comment]
It uses a different device but this is due to an upstream problem breaking the ath79 target.
