### ISSUE TITLE
Requests from OpenWrt don't work (While on the website they work)

### ISSUE THREAD

**Issue by tomjschwanke** [aparcar/asu#169]
OpenWrt 18.06.2 on TL-WDR4300 V1
The luci-app finds possible package upgrades, but clicking on "Request Firmware" just greys out the button and I'm not getting a firmware (I have waited long, even my login timed out).

Builds requested on the Website work fine though.

**Comment by aparcar** [comment]
should be fixed, please try again

**Comment by aparcar** [comment]
https://github.com/aparcar/attendedsysupgrade-server/commit/2c485fc645981dd9a2c5c7c6b77e93e7a28cfd41

**Comment by tomjschwanke** [comment]
Tried it again today. It got to "processing request" which also seemed to load forever, so I refreshed the interface and its back to the above problem.

**Comment by aparcar** [comment]
I see, the request fails and the error response is not (yet) handled by the luci-app... I'm on it

**Comment by Roland-B** [comment]
Same here for WRT32X, but also get Unsupported device, release, target, **_subtraget_** or board  <-- note spelling mistake also for the error.

**Comment by aparcar** [comment]
I reworked the app and web frontend and now everything should work again. If not please reopen
