### ISSUE TITLE
Request firmware returns old firmware

### ISSUE THREAD

**Issue by N1ghtshad0w** [aparcar/asu#174]
Search for upgrades returns with Package upgrades available
Request firmware returns with Firmware created
The problem is the link for the created firmware is for the existing firmware (old) not the one with the package upgrades (new)

**Comment by aparcar** [comment]
Currently build images of "stable" releases are stored for two weeks, I have to implement a way to automatically remove images which contain outdated packages, but that's not that easy.

I'll try to fix it at some point!

**Comment by aparcar** [comment]
What version/release are you building for?

**Comment by N1ghtshad0w** [comment]
> 
> 
> What version/release are you building for?

18.06.04

**Comment by aparcar** [comment]
The current server at https://chef.libremesh.org/ only supports snapshot and 18.06.x can"t be supported due to missing JSON files.
