### ISSUE TITLE
Error building firmware

### ISSUE THREAD

**Issue by N1ghtshad0w** [aparcar/asu#194]
Getting incompatible package selection error when building firmware.
![screenshot-chef libremesh org-2019 08 20-08_49_45](https://user-images.githubusercontent.com/48315620/63324118-b6d40580-c327-11e9-8169-cc5a99bd19fe.png)
https://chef.libremesh.org/download/faillogs/faillog-b03533d17a80.txt

**Comment by aparcar** [comment]
The device is currently affected by an upstream issue breaking all ath79 targets. Please try the new server at https://chef.libremesh.org/

**Comment by aparcar** [comment]
Works again at https://chef.libremesh.org/

![image](https://user-images.githubusercontent.com/16000931/76023246-dfd77480-5ecc-11ea-8f91-6483b1a99a32.png)
