### ISSUE TITLE
Linksys EA8300 snapshots (New FrontEnd)

### ISSUE THREAD

**Issue by syto203** [aparcar/asu#198]
**Describe the bug**
unable to choose linksys ea8300 in the new frontend [https://sudhanshu16.github.io/openwrt-firmware-selector)/](https://sudhanshu16.github.io/openwrt-firmware-selector)/) works normally on [https://aparcar.stephen304.com](https://aparcar.stephen304.com) .

the new frontend page throws the error "An unexpected error occurred. Please try again"
and the console reports "Request failed with status code 404".

**Comment by ich0x** [comment]
@syto203 The server was down when you wrote the issue, and it remains down as of now.

**Comment by aparcar** [comment]
I'll have to rebuild all the images, will do that later

**Comment by aparcar** [comment]
Works on the new server https://chef.libremesh.org/
![image](https://user-images.githubusercontent.com/16000931/75199412-20820180-5707-11ea-8980-27d7173dfbfa.png)
