### ISSUE TITLE
Linksys WRT1900ACS Can't Build Snapshot (New Frontend)

### ISSUE THREAD

**Issue by Crusader144** [aparcar/asu#202]
I was able to use this page to create my Snapshot image https://aparcar.stephen304.com/  now this new front end page does not have the Linksys wrt1900acs https://sudhanshu16.github.io/openwrt-firmware-selector/

**Comment by aparcar** [comment]
Works with the new server at https://chef.libremesh.org

![image](https://user-images.githubusercontent.com/16000931/75198910-d2b8c980-5705-11ea-8ded-4da42f66c9d0.png)
