### ISSUE TITLE
Can't create images for Raspberry Pi 3B/3B+

### ISSUE THREAD

**Issue by code403** [aparcar/asu#203]
Hello, i keep getting an error "An unexpected error occurred. Please try again" if i try to create images (18.06.4/Snapshot) for all Raspberry Pi devices

**Comment by ich0x** [comment]
A bunch of targets are inactive on the imagebuilder at the moment, what is happening to this target brcm2708/* also is happening to the ramips/mt7621 grouping as well

**Comment by Slluxx** [comment]
still an issue. this is probably the only way i can offline install luci on my raspi (as im in a dorm with very specific one-device-only access and bridge'ing doesnt work)

please fix

**Comment by aparcar** [comment]
Works with the new server https://chef.libremesh.org/

![image](https://user-images.githubusercontent.com/16000931/75201868-bde03400-570d-11ea-97f9-3b570ce00247.png)
