### ISSUE TITLE
Zbtlink ZBT-APE522II unexpected error

### ISSUE THREAD

**Issue by jkimmel** [aparcar/asu#206]
unexpected error comes up for Snapshot 19.07 and 18.06 .
Snapshot isn't available at all

**Comment by aparcar** [comment]
Currently a problem of upstream... https://chef.libremesh.org/store/SNAPSHOT/ramips/mt7620/zbtlink_zbt-ape522ii/e3b0c44298fc/buildlog.txt

**Comment by jkimmel** [comment]
> Currently a problem of upstream... https://chef.libremesh.org/store/SNAPSHOT/ramips/mt7620/zbtlink_zbt-ape522ii/e3b0c44298fc/buildlog.txt
> 
not working (404)

**Comment by aparcar** [comment]
https://chef.libremesh.org/store/SNAPSHOT/ramips/mt7620/zbtlink_zbt-ape522ii/e3b0c44298fc/buildlog.txt

Changed the storage path - sorry...

**Comment by aparcar** [comment]
Works again

![image](https://user-images.githubusercontent.com/16000931/76022992-588a0100-5ecc-11ea-852d-ac186ad72137.png)
