### ISSUE TITLE
Support x86 images

### ISSUE THREAD

**Issue by chancat87** [aparcar/asu#207]
Is there support for x86 and x64?

**Comment by aparcar** [comment]
Currently not as the build process don't create any JSON files yet, which is required by the front end to know which images were actually created.

I'll try to fix this upstream but it might take a while - sorry

**Comment by aparcar** [comment]
I created an upstream patch for that https://github.com/openwrt/openwrt/pull/2772

**Comment by aparcar** [comment]
The patch is accepted and I have to integrate it into the build system.

**Comment by Toomoch** [comment]
was support implemented?

**Comment by FreifunkUFO** [comment]
on http://chef.libremesh.org/ now i can choose  Generic x86/64 on SNAPSHOT.
but, build throw an error
`opkg_install_cmd: Cannot install package procd.`
https://chef.libremesh.org/store/snapshot/x86/64/generic/e3b0c44298fc/buildlog.txt

**Comment by aparcar** [comment]
Support for x86 packages was added some time ago.

**Comment by aparcar** [comment]
![image](https://user-images.githubusercontent.com/16000931/111086344-b5e16680-84bf-11eb-9e3f-13d73b233773.png)
