### ISSUE TITLE
Certificate expired on https://chef.libremesh.org/

### ISSUE THREAD

**Issue by Legogris** [aparcar/asu#210]
Can no longer perform attended sysupgrades via Luci due to server certificate expired on 2019-12-06.

**Comment by mainmachine** [comment]
This really shouldn't be a problem with how easy Letsencrypt is to automate.

I've done it many ways on many servers and I would be happy to offer help if it will get this working. Just started using the current OpenWRT after using Tomato for years, and loving it...

**Comment by aparcar** [comment]
Thanks for letting me know, I kinda lost access to the server for a while. Should work again.
