### ISSUE TITLE
imagebuilder timeout

### ISSUE THREAD

**Issue by ghoffman9** [aparcar/asu#238]
apacar -
your online imagebuilder is timing out for any new build this AM
https://chef.libremesh.org/
(at least for wrt1900 v1)

good morning and best wishes for health

**Comment by aparcar** [comment]
Please retry

**Comment by ghoffman9** [comment]
This is what I get:

Previously it took 180 sec to give this.

Now – on a different computer – it was immediate.

**Comment by aparcar** [comment]
Hi, In case the servers from downloads.openwrt.org are to slow the build timeouts, I updated the timeout to 5 minutes and will try to use the faster CDN in the future. Please retry and close this issue if resolved.

**Comment by ghoffman9** [comment]
Seems to work – great – thank you!

**Comment by ghoffman9** [comment]
@aparcar -
another imagebuilder hangup.
for the past two days, it has ended with this error:
![image](https://user-images.githubusercontent.com/24581429/77903574-b77f3380-7248-11ea-9e92-40ae31fb6fe8.png)
[imagebuildererror.txt](https://github.com/aparcar/asu/files/4402187/imagebuildererror.txt)

**Comment by aparcar** [comment]
Seems to be an upstream issue and multiple devices are affected https://github.com/openwrt/openwrt/commit/2d61f8821c7cf99354e904139226c132554ba180

**Comment by aparcar** [comment]
https://patchwork.ozlabs.org/patch/1264611/

**Comment by ghoffman9** [comment]
Very good catch. Thank you

George

**Comment by aparcar** [comment]
Should be fixed.
