### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by shaman79** [aparcar/asu#243]
I tried to use luci app with this result. Is it supposed to be working or is it still WIP?

![obrazek](https://user-images.githubusercontent.com/35869063/77697026-5c321480-6fae-11ea-82a5-22c7a650fc7f.png)

luci-app-attendedsysupgrade - git-20.081.71863-12f0dac-1

**Comment by aparcar** [comment]
Please install the app version `git-20.086.76556-9edb933-1`. Anything apart snapshots is currently not supported as there is no JSON info file support in current stable versions.
