### ISSUE TITLE
AssertionError: ImageBuilder failed (installing luci-app-sqm fails)

### ISSUE THREAD

**Issue by sinancetinkaya** [aparcar/asu#249]
any idea why installing luci-app-sqm fails?

[buildlog.txt](https://github.com/aparcar/asu/files/4578307/buildlog.txt)

**Comment by aparcar** [comment]
So this fixed itself?

**Comment by sinancetinkaya** [comment]
I removed sqm package. I thought it was package related, wasn't it?

**Comment by sinancetinkaya** [comment]
I just tried to install it via Luci and got the same error.

> Required dependency package kmod-sched-cake-oot is not available in any repository.

So it's package related.
