### ISSUE TITLE
ASU with X-WRT

### ISSUE THREAD

**Issue by Noruas29** [aparcar/asu#255]
I'm using X-WRT (OpenWRT fork for Xiaomi) and I want to use ASU with this adress:
https://downloads.x-wrt.com/rom/

With the good ROM search: xiaomi_miwifi-r3

I tried many things but nothing works.... any suggestions ?

**Comment by aparcar** [comment]
Hi, please ask them to provide an ImageBuilder. Without that it's not possible to build their images.

Also they have to enable JSON creation which allows the web interface to show the appropriate information.

**Comment by aparcar** [comment]
Closing due to no response.
