### ISSUE TITLE
assertion error  or nginx not found when building for wrt3200 / 19.07.5

### ISSUE THREAD

**Issue by ghoffman9** [aparcar/asu#261]
when the server first offered 19.07.5 builds, i got 1 image built. since jan 24 at least,, cant get anything working 
attempts to download without modifiers leads to nginx error
attempt to build custom immage gives assertion error or just hang

fyi and thank you

**Comment by aparcar** [comment]
You just select the package `nginx`? I just tried with 19.07.6 and 19.07.7 and it worked out fine...

**Comment by aparcar** [comment]
Please ping me if the issue s still relevant for you
