### ISSUE TITLE
TP Link Archer MR200 v4 support needed

### ISSUE THREAD

**Issue by Mctifa** [aparcar/asu#264]
Please add the TP Link Archer MR200 v4 firmware to the list as I cannot find it.

**Comment by aparcar** [comment]
It's available, I accidentally messed something up in the fronted. Please retry.

![image](https://user-images.githubusercontent.com/16000931/107450108-c3828580-6ae8-11eb-9aaf-0682a50f0d62.png)

**Comment by Mctifa** [comment]
@aparcar please note that this is not for v4

**Comment by aparcar** [comment]
Is the device support by OpenWrt? If not, the server can't build the image.

**Comment by aparcar** [comment]
This commit never made it into upstream OpenWrt: https://github.com/Mctifa/mr200v4/commit/87418bafc8fd1151eed32d265f956d168c50efc1

**Comment by Mctifa** [comment]
Thank you for the heads up
I will try to build it and see

**Comment by asaorgad** [comment]
Hi , so from all the discussion above, i didnt understood, is there a support for openwrt for mr200 v4 ? If yes can someone pleae send me the link to the firmware .?

**Comment by aparcar** [comment]
@asaorgad it's not part of OpenWrt, you could ask @Mctifa to send the link to upstream.
