### ISSUE TITLE
version in 19.07.7 (latest stable) not working ?

### ISSUE THREAD

**Issue by CHazz** [aparcar/asu#277]
hi i try for check few times in many versions of openwrt but never work ..
now have 19.07.7 and again nothing ..  no way 

root@OpenWrt:~# auc
auc (0.1.4)
running OpenWrt 19.07.7 on ath79/generic (tplink,archer-c7-v5)
checking https://chef.libremesh.org/ for release upgrade or updated packages
HTTP error 404
server reply invalid.

**Comment by aparcar** [comment]
I'm sorry for the inconvenience, @dangowrt and me did some efforts to make the experience much better in version 21.02 an onward. Please try the latest 21.02.0-rc1

**Comment by richb-hanover** [comment]
I also saw this error message (Netgear WNDR3800 running 19.07.7). Is it the same situation? (I am not asking for any change - I'm totally fine with holding the ASU until we ship 21.02...)

<img width="958" alt="image" src="https://user-images.githubusercontent.com/1094930/116256330-17445880-a741-11eb-903f-e4314923eea1.png">

**Comment by CHazz** [comment]
in 21.02.0-rc1 working :) Thank you and Good Luck

**Comment by CHazz** [comment]
i try flast to snapshot .. working . is possible flash bact to future stable version from luci ?

**Comment by richb-hanover** [comment]
I get a permanent "Searching for an available sysupgrade" hang in the LuCI GUI... (I'm using 19.07.7 on Linksys WRT3200ACM).

Is this the same symptom? Should I just upgrade to 21.02 manually? Thanks.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/1094930/129588420-43d2bf99-0ba9-4480-8800-76b0ea07af18.png">

**Comment by aparcar** [comment]
@richb-hanover can you give an update on this? still facing the issue?

**Comment by richb-hanover** [comment]
Solved. I went to the router (running 19.07.7) and clicked "Search for sysupgrade"

I got a spinner for a couple seconds (I think) then was presented with the option to upgrade to 19.07.8. There were no other choices in the dropdown. The router is in production now, so I did not try the upgrade. I will try it next weekend.

Thanks!

**Comment by aparcar** [comment]
Please let me know how it goes.

**Comment by aparcar** [comment]
Updates on this?

**Comment by richb-hanover** [comment]
Alas... I have been extremely busy and the site where that router is installed has been in production with lots of users. I did go to the GUI and it offered to build and then download, but I (again) decided not to do it. Perhaps you could close this (the original problem I reported seems fixed) and I will re-open if I see a problem when I actually upgrade. Thanks.

**Comment by richb-hanover** [comment]
@aparcar Using luci-app-attendedsysupgrade git-21.267.59215-1524972-1 on OpenWrt 19.07.7 on Linksys WRT3200ACM. LuCI says "Powered by LuCI openwrt-19.07 branch (git-21.044.30835-34e0d65) / OpenWrt 19.07.7 r11306-c4a6851c72" at the bottom of each page.

I went to **System -> Attended Sysupgrade** and was given the choice of 19.07.8. I clicked "Request sysupgrade" and immediately got the following error window:

**Error building the sysupgrade**
Unsupported package(s): libubus20191227
**Please report the error message and request**

Request to server:
```
Request to server:
{
"board_name": "linksys,rango",
"target": "mvebu/cortexa9",
"version": "19.07.8",
"packages": [
"base-files",
"busybox",
"cgi-io",
"dnsmasq",
"dropbear",
"firewall",
"fstools",
"fwtool",
"getrandom",
"ip6tables",
"iptables",
"iwinfo",
"jshn",
"jsonfilter",
"kernel",
"kmod-btmrvl",
"kmod-gpio-button-hotplug",
"kmod-ip6tables",
"kmod-ipt-conntrack",
"kmod-ipt-core",
"kmod-ipt-nat",
"kmod-ipt-offload",
"kmod-lib-crc-ccitt",
"kmod-mwifiex-sdio",
"kmod-mwlwifi",
"kmod-nf-conntrack",
"kmod-nf-conntrack6",
"kmod-nf-flow",
"kmod-nf-ipt",
"kmod-nf-ipt6",
"kmod-nf-nat",
"kmod-nf-reject",
"kmod-nf-reject6",
"kmod-ppp",
"kmod-pppoe",
"kmod-pppox",
"kmod-slhc",
"libblobmsg-json",
"libip4tc2",
"libip6tc2",
"libiwinfo-lua",
"libiwinfo20181126",
"libjson-c2",
"libjson-script",
"liblua5.1.5",
"liblucihttp-lua",
"liblucihttp0",
"libnl-tiny",
"libubox20191228",
"libubus-lua",
"libubus20191227",
"libuci20130104",
"libuclient20160123",
"libxtables12",
"logd",
"lua",
"luci",
"luci-app-attendedsysupgrade",
"luci-app-firewall",
"luci-app-opkg",
"luci-app-snmpd",
"luci-app-sqm",
"luci-app-wireguard",
"luci-base",
"luci-lib-ip",
"luci-lib-jsonc",
"luci-lib-nixio",
"luci-mod-admin-full",
"luci-mod-network",
"luci-mod-status",
"luci-mod-system",
"luci-proto-ipv6",
"luci-proto-ppp",
"luci-theme-bootstrap",
"mtd",
"mwlwifi-firmware-88w8964",
"nano",
"netifd",
"odhcp6c",
"odhcpd-ipv6only",
"openwrt-keyring",
"opkg",
"ppp",
"ppp-mod-pppoe",
"procd",
"rpcd",
"rpcd-mod-file",
"rpcd-mod-iwinfo",
"rpcd-mod-luci",
"rpcd-mod-rrdns",
"snmpd",
"swconfig",
"ubi-utils",
"uboot-envtools",
"ubox",
"ubus",
"ubusd",
"uci",
"uclient-fetch",
"uhttpd",
"urandom-seed",
"urngd",
"usign",
"wireguard",
"wpad-basic"
],
".anonymous": false,
".name": "request",
".type": "request",
".index": 0
}
```

**Comment by aparcar** [comment]
Which server are you using?

**Comment by richb-hanover** [comment]
I changed the config tab to use `https://asu.aparcar.org` (it was chef.libremesh.org), and got the same error.
 
It's complaining about `libubus20191227` - is that a problem?

**Comment by richb-hanover** [comment]
**More info:** I uninstalled `luci-app-attendedsysupgrade` and went to re-install it. I got this list of packages that would be installed:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/1094930/135170839-f0081ab4-ff7b-4ec5-a81a-64b531de94cf.png">

and here's the installation report:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/1094930/135171069-2bddfa0b-c72b-4644-8a33-b46f41fed4dc.png">

Re-attempting the attended sysupgrade gets the same error message.

**Comment by aparcar** [comment]
What is the content of /etc/config/attendedsysupgrade

**Comment by richb-hanover** [comment]
Contents of /etc/config/attendedsysupgrade

```
config server 'server'
	option url 'https://asu.aparcar.org'

config client 'client'
	option upgrade_packages '1'
	option auto_search '0'
	option advanced_mode '0'
```

**Comment by aparcar** [comment]
Fixed via https://github.com/aparcar/asu/commit/bfecd216f362766cde3dfaa137fb0043e0c8bb79

**Comment by aparcar** [comment]
Please start using `https://sysupgrade.openwrt.org` as upgrade server.

**Comment by richb-hanover** [comment]
That new upgrade server seems to have worked... I did not actually perform the upgrade since the router is in production. I'll update if I have problems. Thanks!

<img width="627" alt="image" src="https://user-images.githubusercontent.com/1094930/135276784-1fd633b8-29df-42f5-9bc2-afb3b8bbbe73.png">
