### ISSUE TITLE
Add device model

### ISSUE THREAD

**Issue by CyberHead** [aparcar/asu#280]
TP-Link EAP225-Outdoor v1 in 19.07.6 release

**Comment by aparcar** [comment]
The device is only available in later releases, please try OpenWrt 21.02.0-rc2.

**Comment by CyberHead** [comment]
unstable

**Comment by aparcar** [comment]
The 21.02 should be fairly stable, if not, please wait until the full release.

**Comment by dangowrt** [comment]
> unstable

Apart from this being the wrong place (PR on https://github.com/openwrt/openwrt/tree/openwrt-19.07 would be the right way), I guess it's a bit too late to request backports for 19.07 now that 21.02 is around the corner.
