### ISSUE TITLE
Chef.libremesh.org customized image

### ISSUE THREAD

**Issue by locussss** [aparcar/asu#284]
Hi!

I am trying to build a customized image the last two days but  https://chef.libremesh.org/api/build gives status 404.

<img width="1566" alt="404" src="https://user-images.githubusercontent.com/58507126/127527144-303e6f5d-0d90-4755-b75b-311f497699ce.png">

**Comment by grauerfuchs** [comment]
I'm seeing the same thing both with requests to /api/latest and /api/build. It looks like the build system is down.

**Comment by aparcar** [comment]
Server is down. Once I have proper internet I'll restart it and see how to make it more resilient against reboots

**Comment by dhcpme** [comment]
Thanks, Paul!

**Comment by aparcar** [comment]
Restarted.

**Comment by jamesmacwhite** [comment]
The API appears down again, just an FYI.
