### ISSUE TITLE
Raspberry pi 4b profile error with attendedsysupgrade

### ISSUE THREAD

**Issue by locussss** [aparcar/asu#292]
Hi!

Attended sysupgrade through luci is super!

I only have one question (bug?).

When in luci-app-attendedsysupgrade I search for sysupgrade I get the popup dialog which shows me the installed packages with the Board Name/Profile "raspberrypi,4-model-b". This is already pre-filled for me, see screenshot.
<img width="1348" alt="1-popup-dialog" src="https://user-images.githubusercontent.com/58507126/129590440-de2af9b8-7a24-4aee-94e8-802fe6dca012.png">

I click request sysupgrade and then I get this error, see screenshot.
<img width="1392" alt="2-popop-error" src="https://user-images.githubusercontent.com/58507126/129590511-0d74af43-1904-418e-a2c7-3cdad7be73d7.png">

If I replace in Board name/Profile "raspberrypi,4-model-b" with "rpi-4" it runs okay and builds an image.
Why can't it be saved with the correct profile?
I have to change everytime into "rpi-4".

**Comment by wulfy23** [comment]
i'm also seeing unsupported profile rpi-2 on the rpi-4

**Comment by aparcar** [comment]
Fixed via https://github.com/aparcar/asu/commit/d8ca0f303c01fa1390b373b740789683af102a94 please try again on https://asu.aparcar.org.

**Comment by locussss** [comment]
I can confirm it is working now.

Thanks!
