### ISSUE TITLE
KeyError: 'JSON_PATH' 

### ISSUE THREAD

**Issue by richb-hanover** [aparcar/asu#304]
I decided to look at #302, and so I followed the instructions for [creating a development server.](https://github.com/aparcar/asu#development) No errors, but note the warning about using pip 19.0.3 instead of 21.2.4 in the `details` below.

I went to localhost:5000 and the browser immediately showed the error below.  Thoughts on fixing the JSON_PATH problem?

<blockquote>
KeyError

KeyError: 'JSON_PATH'
Traceback (most recent call last)

    File "/Users/richb/github/asu/.direnv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/Users/richb/github/asu/.direnv/lib/python3.7/site-packages/flask/cli.py", line 83, in find_best_app

    app = call_factory(script_info, app_factory)

    File "/Users/richb/github/asu/.direnv/lib/python3.7/site-packages/flask/cli.py", line 119, in call_factory

    return app_factory()

    File "/Users/richb/github/asu/asu/asu.py", line 103, in create_app

    (app.config["JSON_PATH"] / "branches.json").write_text(

    KeyError: 'JSON_PATH'
</blockquote>

<details>

<summary>Click to see installation log</summary>

<pre>
√ github % cd asu
√ asu % python3 -m menv .direnv
/Users/richb/.pyenv/versions/3.7.4/bin/python3: No module named menv
?1 asu % python3 -m venv .direnv
√ asu % source .direnv/bin/activate
(.direnv) √ asu % pip install -r requirements.txt
Collecting attrs==21.2.0 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/20/a9/ba6f1cd1a1517ff022b35acd6a7e4246371dfab08b8e42b829b6d07913cc/attrs-21.2.0-py2.py3-none-any.whl
Collecting certifi==2021.5.30 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/05/1b/0a0dece0e8aa492a6ec9e4ad2fe366b511558cdc73fd3abc82ba7348e875/certifi-2021.5.30-py2.py3-none-any.whl
Collecting cffi==1.14.6 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/a2/4e/6225779f1ccb7916cd6c640ca4dbe6e0ce1452952bb822d66d5e875a6f53/cffi-1.14.6-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting charset-normalizer==2.0.4 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/33/53/b7f6126a2b9fd878b025fe3c40266cfaad696f312165008ce045bffa3fe7/charset_normalizer-2.0.4-py3-none-any.whl
Collecting click==7.1.2 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting clickclick==20.10.2 (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/7a/7e/c08007d3fb2bbefb430437a3573373590abedc03566b785d7d6763b22480/clickclick-20.10.2-py2.py3-none-any.whl
Collecting connexion[swagger-ui]==2.9.0 (from -r requirements.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/a7/4a/e6d1884956c674e3cb440bb8976fd4a635692f4084eaa7b6465f508c576e/connexion-2.9.0-py2.py3-none-any.whl
Collecting flask==1.1.4 (from -r requirements.txt (line 24))
  Using cached https://files.pythonhosted.org/packages/e8/6d/994208daa354f68fd89a34a8bafbeaab26fda84e7af1e35bdaed02b667e6/Flask-1.1.4-py2.py3-none-any.whl
Collecting idna==3.2 (from -r requirements.txt (line 26))
  Using cached https://files.pythonhosted.org/packages/d7/77/ff688d1504cdc4db2a938e2b7b9adee5dd52e34efbd2431051efc9984de9/idna-3.2-py3-none-any.whl
Collecting inflection==0.5.1 (from -r requirements.txt (line 28))
  Using cached https://files.pythonhosted.org/packages/59/91/aa6bde563e0085a02a435aa99b49ef75b0a4b062635e606dab23ce18d720/inflection-0.5.1-py2.py3-none-any.whl
Collecting isodate==0.6.0 (from -r requirements.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl
Collecting itsdangerous==1.1.0 (from -r requirements.txt (line 32))
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting jinja2==2.11.3 (from -r requirements.txt (line 34))
  Using cached https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl
Collecting jsonschema==3.2.0 (from -r requirements.txt (line 38))
  Using cached https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl
Collecting markupsafe==2.0.1 (from -r requirements.txt (line 43))
  Using cached https://files.pythonhosted.org/packages/75/90/b780381ddf38e2afd07a04746b5d3158a085464f7c757fc62cd198aa5379/MarkupSafe-2.0.1-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting openapi-schema-validator==0.1.5 (from -r requirements.txt (line 45))
  Using cached https://files.pythonhosted.org/packages/61/de/67a615be34d76a1b18ee13861ffd584ffc982e465499c67d5b029bd1084a/openapi_schema_validator-0.1.5-py3-none-any.whl
Collecting openapi-spec-validator==0.3.1 (from -r requirements.txt (line 47))
  Using cached https://files.pythonhosted.org/packages/32/a7/4030c3b0bbd08ddb09186d50e7bfddcb439733ac3d542e3038e5b2fc0d44/openapi_spec_validator-0.3.1-py3-none-any.whl
Collecting pycparser==2.20 (from -r requirements.txt (line 49))
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Collecting pynacl==1.4.0 (from -r requirements.txt (line 51))
  Using cached https://files.pythonhosted.org/packages/d4/68/a84e1cc99e4b08f857f148ba5ff6653afb954e121e8362c7a6242d8755ef/PyNaCl-1.4.0-cp35-abi3-macosx_10_10_x86_64.whl
Collecting pyrsistent==0.18.0 (from -r requirements.txt (line 53))
  Using cached https://files.pythonhosted.org/packages/d4/63/5ef75e0e19154787bee90b0bf1567237e67c56e1d6b8ea117829a3f7c6a9/pyrsistent-0.18.0-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting pyyaml==5.4.1 (from -r requirements.txt (line 55))
  Using cached https://files.pythonhosted.org/packages/6b/8c/674cc47282af12bd7f12eea6cc87d907ada593b15f5ba0b51638599500c9/PyYAML-5.4.1-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting redis==3.5.3 (from -r requirements.txt (line 60))
  Using cached https://files.pythonhosted.org/packages/a7/7c/24fb0511df653cf1a5d938d8f5d19802a88cef255706fdda242ff97e91b7/redis-3.5.3-py2.py3-none-any.whl
Collecting requests==2.26.0 (from -r requirements.txt (line 64))
  Using cached https://files.pythonhosted.org/packages/92/96/144f70b972a9c0eabbd4391ef93ccd49d0f2747f4f6a2a2738e99e5adc65/requests-2.26.0-py2.py3-none-any.whl
Collecting rq==1.10.0 (from -r requirements.txt (line 68))
  Using cached https://files.pythonhosted.org/packages/cf/70/85fa7584932ab6199fa376a8e1aade4b1a7c12e09478785674448e16587b/rq-1.10.0-py2.py3-none-any.whl
Collecting six==1.16.0 (from -r requirements.txt (line 70))
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting swagger-ui-bundle==0.0.8 (from -r requirements.txt (line 76))
  Using cached https://files.pythonhosted.org/packages/bf/f3/4d370b25c6a23f44d6e6d538ff42c13f897b6cf71e7b684aa6aa9779d800/swagger_ui_bundle-0.0.8-py3-none-any.whl
Collecting urllib3==1.26.6 (from -r requirements.txt (line 78))
  Using cached https://files.pythonhosted.org/packages/5f/64/43575537846896abac0b15c3e5ac678d787a4021e906703f1766bfb8ea11/urllib3-1.26.6-py2.py3-none-any.whl
Collecting werkzeug==1.0.1 (from -r requirements.txt (line 80))
  Using cached https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl
Collecting importlib-metadata; python_version < "3.8" (from jsonschema==3.2.0->-r requirements.txt (line 38))
  Using cached https://files.pythonhosted.org/packages/71/c2/cb1855f0b2a0ae9ccc9b69f150a7aebd4a8d815bd951e74621c4154c52a8/importlib_metadata-4.8.1-py3-none-any.whl
Requirement already satisfied: setuptools in ./.direnv/lib/python3.7/site-packages (from jsonschema==3.2.0->-r requirements.txt (line 38)) (40.8.0)
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->jsonschema==3.2.0->-r requirements.txt (line 38))
  Using cached https://files.pythonhosted.org/packages/bd/df/d4a4974a3e3957fd1c1fa3082366d7fff6e428ddb55f074bf64876f8e8ad/zipp-3.6.0-py3-none-any.whl
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata; python_version < "3.8"->jsonschema==3.2.0->-r requirements.txt (line 38))
  Using cached https://files.pythonhosted.org/packages/74/60/18783336cc7fcdd95dae91d73477830aa53f5d3181ae4fe20491d7fc3199/typing_extensions-3.10.0.2-py3-none-any.whl
Installing collected packages: attrs, certifi, pycparser, cffi, charset-normalizer, click, pyyaml, clickclick, idna, urllib3, requests, pyrsistent, six, zipp, typing-extensions, importlib-metadata, jsonschema, isodate, openapi-schema-validator, openapi-spec-validator, werkzeug, itsdangerous, markupsafe, jinja2, flask, inflection, swagger-ui-bundle, connexion, pynacl, redis, rq
Successfully installed attrs-21.2.0 certifi-2021.5.30 cffi-1.14.6 charset-normalizer-2.0.4 click-7.1.2 clickclick-20.10.2 connexion-2.9.0 flask-1.1.4 idna-3.2 importlib-metadata-4.8.1 inflection-0.5.1 isodate-0.6.0 itsdangerous-1.1.0 jinja2-2.11.3 jsonschema-3.2.0 markupsafe-2.0.1 openapi-schema-validator-0.1.5 openapi-spec-validator-0.3.1 pycparser-2.20 pynacl-1.4.0 pyrsistent-0.18.0 pyyaml-5.4.1 redis-3.5.3 requests-2.26.0 rq-1.10.0 six-1.16.0 swagger-ui-bundle-0.0.8 typing-extensions-3.10.0.2 urllib3-1.26.6 werkzeug-1.0.1 zipp-3.6.0
You are using pip version 19.0.3, however version 21.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(.direnv) √ asu % export FLASK_APP=asu.asu
(.direnv) √ asu % export FLASK_DEBUG=1
(.direnv) √ asu % flask run
 * Serving Flask app "asu.asu" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 101-654-913
127.0.0.1 - - [07/Oct/2021 08:15:42] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/richb/github/asu/.direnv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/richb/github/asu/.direnv/lib/python3.7/site-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/Users/richb/github/asu/.direnv/lib/python3.7/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/Users/richb/github/asu/asu/asu.py", line 103, in create_app
    (app.config["JSON_PATH"] / "branches.json").write_text(
KeyError: 'JSON_PATH'
127.0.0.1 - - [07/Oct/2021 08:15:42] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [07/Oct/2021 08:15:42] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Oct/2021 08:15:42] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Oct/2021 08:15:42] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [07/Oct/2021 08:15:42] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
</pre>
</details>

**Comment by aparcar** [comment]
Please try again, should be fixed via https://github.com/aparcar/asu/commit/222c6c6b8ea0fb188ebceeaa38fcaf2e9f6aae5c
