### ISSUE TITLE
feature request: an option to upgrade with unmodified image from OpenWrt

### ISSUE THREAD

**Issue by bam80** [aparcar/asu#311]
Currently, all generated images are custom ones. Their checksums do not match to officially published images.
Could we implement the feature to upgrade with unmodified images, also?

**Comment by aparcar** [comment]
No, how would the router now if it's running a custom or a vanilla image?

Instead we should work upstream on reproducibility of OpenWrt. If you look at the server response it contains the `build_cmd` which allows you to locally "rebuild" the same image. If OpenWrt would be 100% reproducible, it would end up with the same checksum.

Example [here](http://sysupgrade.openwrt.org/api/v1/build/fe3f4deefe736713091f576299cdfa74):

```json
  "build_cmd": [
    "make",
    "image",
    "PROFILE=8dev_carambola2",
    "PACKAGES=auc luci-app-attendedsysupgrade",
    "EXTRA_IMAGE_NAME=08e80e7dbf85",
    "BIN_DIR=/home/aparcar/asu/public/store/fe3f4deefe736713091f576299cdfa74"
  ],
```

**Comment by bam80** [comment]
Does work on reproducibility ongoing? Do we have issue/topic to track?

**Comment by aparcar** [comment]
@bam80 me and @lynxis did some work in the past and every now and then efforts are made. Some time ago I created a script that rebuilds OpenWrt and checks if the checksums are the same as upstream. Find it [here](https://github.com/aparcar/openwrt-rebuilder). I'll work on that some time in the future again but feel free to try it yourself.

**Comment by bam80** [comment]
@aparcar Oh cool, maybe include https://github.com/aparcar/openwrt-rebuilder to a `asu` pipeline somehow?

**Comment by aparcar** [comment]
The missing part is more that people make things reproducible, the openwrt-rebuilder is just a tool to show *what* is not reproducible.

**Comment by aparcar** [comment]
As commented [here](https://github.com/openwrt/packages/issues/17095#issuecomment-964447780), offering "default" packages is not implemented right now and the gain is to low compared to the work it comes with.

If you want better reproducibility, please be my guest and report differences between the firmware created by ASU and the Buildbots. Please use [diffoscope](https://diffoscope.org/) to show on a file basis what's different so we can work on that.
