### ISSUE TITLE
Save a copy of the image

### ISSUE THREAD

**Issue by chuacw** [aparcar/asu#315]
Provide a way to save a copy of the image before sysupgrade.

Currently, there's no way to save it.

**Comment by aparcar** [comment]
Using `arc` shows you the full download URL, using the LuCI app you can click on the filename to download it.

**Comment by chuacw** [comment]
I checked using auc --arc but I don't see the full download URL.
Is there some flag I need to set to see it?

![image](https://user-images.githubusercontent.com/1757930/151372701-756f0b2f-b1b0-49c3-89ef-0a68fc1ed0ce.png)


As for the LuCI app, I don't see where I can see the filename either.
Are we talking about the same Unattended Sysupgrade app?

![image](https://user-images.githubusercontent.com/1757930/151372641-667087d4-bb49-44da-ae72-b0ab199d48b5.png)

**Comment by dangowrt** [comment]
I've added a option `-n` to `auc` to allow users to only request the image but not download or sysupgrade anything (dry-run).
https://github.com/openwrt/packages/commit/19c135685f7b9eefbf75b5a96b780f4fa2b46f19

**Comment by chuacw** [comment]
There's no blue text.

![image](https://user-images.githubusercontent.com/1757930/151464388-4b50f9eb-ba44-4421-9bc0-d6b754b25c5c.png)

**Comment by chuacw** [comment]
@dangowrt I would love for the app to have the ability to download, and show where it downloaded the image to, so that the user can save a copy of the image, prompt to continue, before starting the upgrade.

Currently, as a user, there's no way from the CLI to make a copy of the image.

**Comment by dangowrt** [comment]
@chuacw I've just added that feature to `auc`, you can now call `auc -n` to request the image and show the download URL, but not carry out the download or sysupgrade.
https://github.com/aparcar/asu/issues/315#issuecomment-1023470485
https://github.com/openwrt/packages/commit/19c135685f7b9eefbf75b5a96b780f4fa2b46f19

**Comment by chuacw** [comment]
Hi @dangowrt yes, before I posted my previous response, I've already seen your response that you've added "-n".
My request is to save the image, not just provide the download URL.

**Comment by dangowrt** [comment]
Once you got the URL, you can use `wget` (aka. `uclient-fetch`) to download it to `/tmp`...?

**Comment by chuacw** [comment]
When auc is called to perform the upgrade, it already downloads the image to the system.
Display where it downloaded the image to and pausing at this point (with a prompt) to allow the user to copy out the image from the system.

**Comment by chuacw** [comment]
auc doesn't show the URL at all.

![image](https://user-images.githubusercontent.com/1757930/151499140-d84c07f2-fc63-492b-a2a4-ea109d5430b6.png)

![image](https://user-images.githubusercontent.com/1757930/151499246-073ee5cb-deea-48dd-945e-751da09edd40.png)

**Comment by dangowrt** [comment]
It has just been committed to https://github.com/openwrt/packages/ repository (which, btw, would be the right place to file issues for `auc`, this repository is about the server side only). This means you still have to update the package on your device, and you can do that once the buildbot has created new binaries (that may take up to 2 days). So unsurprisingly, you can't enjoy that new feature just yet, just because I've added it in git it won't instantly be available in your device...
