### ISSUE TITLE
auc: remove https dependence

### ISSUE THREAD

**Issue by aparcar** [aparcar/asu#92]
checking the images manually or via usign should be possible

**Comment by dangowrt** [comment]
why? I deliberately made HTTPS mandatory as 'checking images' in which way ever is currently not possible as the worker's pubkey is not present on the target system.

**Comment by aparcar** [comment]
I could download the image and then check the sha256 which is also available at the server viewable on via https

**Comment by aparcar** [comment]
Use case, I install auc on my 841, it checks for an upgrade and requests the image. The image won't be downloaded but a download URL presented to the user. It's then possible to download the image via browser (https) and use scp to upload the image to the router. 

It's may a strange use case but currently I'd like to create a sysupgrade for my router but using all packages from /usr/lib/opkg/status result on chef.libremesh.org in an imagesize fail...

**Comment by dangowrt** [comment]
@aparcar: using OpenWrt snapshot...? (you really shouldnt expect that to work/fit on ancient 4m/32m devices)

**Comment by aparcar** [comment]
why wouldn't sysupgrade/auc work on a legacy device? I thoughts thats why they created ar71xx/tiny?

**Comment by dangowrt** [comment]
yes, but on a release (ie. 18.05 or whatever) everything gets stripped, debugging features get switched off etc. then you got those 150kb extra space for mbedtls. On development snapshots you don't.

**Comment by aparcar** [comment]
@dangowrt please update auc that it uses either https or relies on usign certificates, both appear to be a valid verification method. The latter should work out of the box on most devices

**Comment by dangowrt** [comment]
ucert verification is supported by `sysupgrade` itself, so all signature verification can be dropped from online-update clients.

**Comment by aparcar** [comment]
@dangowrt Perfect, please make HTTPS encryption optionally :)

**Comment by dangowrt** [comment]
Well, just because the image is valid and signed, it doesn't mean yet that it's the one I asked for. Bad folks may still use replay attacks to give you a valid and signed image with a different combination of packages, eg. missing NTP support (making TLS MitM much easier) or missing ca-certifficates (which leads to an _accept-all_ situation). Hence I'd still leave HTTPS enabled by default.

**Comment by aparcar** [comment]
OpenWrt ships now with HTTPS as the libs are required for WPA3 anyway.
